resolver: lts-13.17

packages:
- haskus-studio

extra-deps:
- happstack-server-7.5.1.3

flags: {}
extra-package-dbs: []

allow-newer: true

# need Stack 2.0
compiler-repository: http://github.com/hsyl20/ghc/
compiler: ghc-git-87679a3a2d1a5b02f7720a3236364e806e614c55-quick
drop-packages:
   - Cabal
